spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .xhtml
    mvc:
      view:
        prefix: /templates/layout/
        suffix: .xhtml
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  server:
    port: 8080
    error:
      whitelabel:
        enabled: false
    servlet:
      session:
        timeout: 30m
  logging:
    level:
      root: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: i2ZwGpIFW3zljhRbLgQPpe7fg5xqcXdc
            client-secret: o4JCCW3paBGYQOT8JdiyB9mUwiUNTqs3mox8Cposs6oN8IQX9RVdcXXkraautwdb
            scope: openid profile email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Auth0
            provider: auth0
        provider:
          auth0:
            authorization-uri: https://dev-l5f3fqnk4y5amjwt.us.auth0.com/authorize
            token-uri: https://dev-l5f3fqnk4y5amjwt.us.auth0.com/oauth/token
            user-info-uri: https://dev-l5f3fqnk4y5amjwt.us.auth0.com/userinfo
            jwk-set-uri: https://dev-l5f3fqnk4y5amjwt.us.auth0.com/.well-known/jwks.json
            user-name-attribute: sub